Eticaret.WebUI/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eticaret.Core.Entities;
using Eticaret.Data;
using Eticaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;

namespace Eticaret.WebUI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Policy = "AdminPolicy")]

    public class ProductsController : Controller
    {
        private readonly DatabaseContext _context;

        public ProductsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Products.Include(p => p.Brand).Include(p => p.Category);
            return View(await databaseContext.ToListAsync());
        }

        // GET: Admin/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/Products/Create
        public IActionResult Create()
        {
            ViewData["BrandID"] = new SelectList(_context.Brands, "ID", "Name");
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                product.Image = await FileHelper.FileLoaderAsync(Image, "/img/products");

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "ID", "Name", product.BrandID);
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "ID", "Name", product.BrandID);
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile? Image)
        {
            if (id != product.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Image is not null)
                    {
                        if (!string.IsNullOrEmpty(product.Image))
                        {
                            FileHelper.FileRemover(product.Image, "/img/products/");

                        }
                        product.Image = await FileHelper.FileLoaderAsync(Image, "/img/products/");

                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "ID", "Name", product.BrandID);
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Brand)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                if (!string.IsNullOrEmpty(product.Image))
                {
                    FileHelper.FileRemover(product.Image, "/img/products/");

                }
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ID == id);
        }
    }
}

Eticaret.WebUI/Controllers/FavoritesController.cs
using Eticaret.Core.Entities;
using Eticaret.Data;
using Eticaret.Service.Abstract;
using Eticaret.WebUI.ExtensionMethod;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.WebUI.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly IService<Product> _service;

        public FavoritesController(IService<Product> service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            var favoriler = GetFavorites();
            return View(favoriler);
        }

        private List<Product> GetFavorites() 
        {
            return HttpContext.Session.GetJson<List<Product>>("GetFavorites") ?? [];
        }

        public IActionResult Add(int ProductID)
        {
            var favoriler = GetFavorites();
            var product = _service.Find(ProductID);
            if (product != null && !favoriler.Any(x=> x.ID == ProductID)) 
            { 
                favoriler.Add(product);
                HttpContext.Session.SetJson("GetFavorites",favoriler);
                
            }
            return RedirectToAction("Index");
        }
        
        public IActionResult Remove(int ProductID)
        {
            var favoriler = GetFavorites();
            var product = _service.Find(ProductID);
            if (product != null && favoriler.Any(x=> x.ID == ProductID)) 
            { 
                favoriler.RemoveAll(x=> x.ID == product.ID);
                HttpContext.Session.SetJson("GetFavorites",favoriler);
                
            }
            return RedirectToAction("Index");
        }
    }

   
}

Eticaret.WebUI/Controllers/ProductsController.cs
using Eticaret.Core.Entities;
using Eticaret.Data;
using Eticaret.Service.Abstract;
using Eticaret.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eticaret.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IService<Product> _service;

        public ProductsController(IService<Product> service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index(string q = "")
        {
            var databaseContext = _service.GetAllAsync(x=> x.IsActive && x.Name.Contains(q) || x.Description.Contains(q));
            return View(await databaseContext);
        }

  
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _service.GetQueryable()
                .Include(p => p.Brand)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }


            var model = new ProductDetailViewModel()
            {
                Product = product,
                RelatedProducts = _service.GetQueryable().
                Where(x => x.IsActive && x.CategoryID == product.CategoryID && x.ID != product.ID)

            };

            return View(model);
        }
    }
}

Eticaret.WebUI/Views/Products/Details.cshtml
@model ProductDetailViewModel

@{
	ViewData["Title"] = Model.Product.Name;

}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="/img/products/@Model.Product.Image" alt="@Model.Product.Name"></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: @Model.Product.ProductCode</div>
                <div class="small mb-1">Marka: <img  src="/img/@Model.Product.Brand.Logo" style="width:10%"/> @Model.Product.Brand.Name</div>
                <h1 class="display-5 fw-bolder">@Model.Product.Name</h1>
                <div class="fs-5 mb-5">
@*                     <span class="text-decoration-line-through">$45.00</span>
 *@                    <span>₺ @Model.Product.Price.ToString("N2")</span>
                </div>
                <p class="lead">@Model.Product.Description</p>
                <br />
                <h5>Stokta <span class="badge bg-warning">@Model.Product.Stock</span> Adet vardır</h5>
                <br />
                <div class="d-flex">
                    <form asp-action="Add" asp-controller="Cart" class="d-flex">
                        <input type="hidden" name="ProductID" value="@Model.Product.ID"/>
                        <input class="form-control text-center me-3" name="Quantity" id="inputQuantity" type="number" value="1" style="max-width: 5rem">
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Sepete Ekle
                        </button>
                    </form>

                    <form asp-action="Add" asp-controller="Favorites" class="d-flex ms-3">
                        <input type="hidden" name="ProductID" value="@Model.Product.ID" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                            <i class="bi-heart-fill me-1"></i>
                            Favorilere Ekle
                        </button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Related item section -->


<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4 text-center">İlişkili Ürünler</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach (var item in Model.RelatedProducts)
            {
               <partial name="_ProductsView" model="item" />
            }

           
           
        </div>
    </div>
</section>
    

Eticaret.WebUI/Views/Products/Index.cshtml
@model IEnumerable<Product>

@{
	ViewData["Title"] = "Ürünlerimiz";

}


<div class="my-5">
    <h1 class="text-center">Ürünlerimiz</h1>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        @foreach (var item in Model)
        {
            <partial name="_ProductsView" model="item" />
        }

    </div>
</div>